# Generated by Django 2.2.4 on 2019-08-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=128)),
                ('occurance', models.IntegerField()),
            ],
        ),
        migrations.AddIndex(
            model_name='data',
            index=models.Index(fields=['string'], name='app_data_string_a8ef45_idx'),
        ),
    ]
