# Generated by Django 2.2.4 on 2019-08-07 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='data',
            name='app_data_string_a8ef45_idx',
        ),
        migrations.AddIndex(
            model_name='data',
            index=models.Index(fields=['string', 'occurance'], name='app_data_string_b4e1eb_idx'),
        ),
    ]
